spring:
  application:
    name: CodeControl-Backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/codecontrol1
    username: postgres
    password: postgres2024

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

CodeControl-Backend:
  app:
    jwtCookieName: codecontrol-jwt
    jwtRefreshCookieName: codecontrol-jwt-refresh
    jwtSecret: codeControlSecretKey-12345678909876543212345678908765432123456789098761234567890
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 18000000
    refreshTokenSlidingWindowPeriod: 3600000
